// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6ou43MPEYNprQq_-bUtsqW5H9vZmN64',
    appId: '1:915301708165:web:1f23666502c4e3df88d4ec',
    messagingSenderId: '915301708165',
    projectId: 'expansify-ce4d1',
    authDomain: 'expansify-ce4d1.firebaseapp.com',
    storageBucket: 'expansify-ce4d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGH6pe8PvWDSHFIDWF4_HUL3cQXKR5uhM',
    appId: '1:915301708165:android:7174d95eb4eae33e88d4ec',
    messagingSenderId: '915301708165',
    projectId: 'expansify-ce4d1',
    storageBucket: 'expansify-ce4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DsWsM9P0vWG32hT2JfZ4GWMpNy4k8yk',
    appId: '1:915301708165:ios:0806d81207ecb91388d4ec',
    messagingSenderId: '915301708165',
    projectId: 'expansify-ce4d1',
    storageBucket: 'expansify-ce4d1.firebasestorage.app',
    iosBundleId: 'com.example.socialMediao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy6ou43MPEYNprQq_-bUtsqW5H9vZmN64',
    appId: '1:915301708165:web:1f7086b03e5a8d1288d4ec',
    messagingSenderId: '915301708165',
    projectId: 'expansify-ce4d1',
    authDomain: 'expansify-ce4d1.firebaseapp.com',
    storageBucket: 'expansify-ce4d1.firebasestorage.app',
  );
}
